### ISSUE TITLE
Packaging for production ignores node-modules

### ISSUE THREAD

**Issue by mhashmi** [vitalybe/ReactNativeUniversal#1]
Node modules don't seem to get packaged when running desktop-build. As a very simply example, if we install lodash and simply require it in index.web.js, creating a production build, though successful, resulting in an error when the executable is run (module lodash not found). 

Not very familiar with webpack so simply reporting the issue for now -- if I do manage to fix the problem I'll do a pull request.

**Comment by vitalybe** [comment]
Sorry, I didn't get the chance to check the issue. How was it resolved?

**Comment by mhashmi** [comment]
The issue wasn't with the provided base; I have multiple entry points from main.electron.js which necessitates a slightly different configuration. My apologies I closed the issue without comment -- should have noted that your provided solution works perfectly as is. 

Also, thanks for this project, greatly helped me in getting started!

**Comment by vitalybe** [comment]
Glad to hear it! Good luck with your project.
